language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - WEBDRIVER=selenium
  - WEBDRIVER=phantomjs

matrix:
  allow_failures:
   - php: hhvm

before_script:
  - composer install --prefer-source --no-interaction --no-progress

  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 > /dev/null
  - sudo sed -i -e "s,/var/www,$(pwd)/vendor/behat/mink/tests/Behat/Mink/Driver/web-fixtures,g" /etc/apache2/sites-available/default
  - sudo cp $(pwd)/features/bootstrap/music-ant.local /etc/apache2/site-enabled
  - sudo sed -i -e "s,%webdir%,$(pwd),g" /etc/apache2/sites-enabled/music-ant.local
  - sudo /etc/init.d/apache2 restart

script:
  - vendor/bin/behat
