language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - WEBDRIVER=selenium
  - WEBDRIVER=phantomjs

matrix:
  allow_failures:
   - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --no-progress

  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5
  - sudo cp $(pwd)/features/bootstrap/music-ant.local /etc/apache2/sites-enabled
  - sudo sed -i -e "s,%webdir%,$(pwd),g" /etc/apache2/sites-enabled/music-ant.local
  - sudo /etc/init.d/apache2 restart
  - echo "127.0.0.1 music-ant.local" | sudo tee -a /etc/hosts

script:
  - vendor/bin/behat
